const CategoryListData = {
  'type': 'FeatureCollection',
  'features':
    [
      {
        "storeId": "1003",
        'lat': 38.42827318315666,
        'lng': -121.48146743178536,
        "fullAddress": "2323 Laguna Blvd. Elk Grove, CA 95758",
        "brand": "76",
        "storeBrand": "Power Market",
        "businessHours": "24/7",
        "email": "1003@hasoil.com",
        "address": "2323 Laguna Blvd.",
        "city": "Elk Grove",
        "state": "CA",
        "county": "Sacramento",
        "zip": "95758",
        "phone": "(916) 244-0070",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "",
        "deli": "",
        "fee-osp": "",
        "carwash": "Drive Thru",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Bulk",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "1004",
        'lat': 38.424142604880224,
        'lng': -121.37207570294973,
        "fullAddress": "9198 Elk Grove-Florin Rd. Elk Grove, CA 95624",
        "brand": "76",
        "storeBrand": "Power Market",
        "businessHours": "24/7",
        "email": "1004@hasoil.com",
        "address": "9198 Elk Grove-Florin Rd.",
        "city": "Elk Grove",
        "state": "CA",
        "county": "Sacramento",
        "zip": "95624",
        "phone": "(916) 244-0080",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "",
        "deli": "",
        "fee-osp": "",
        "carwash": "Drive Thru",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage & Bulk",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "1005",
        'lat': 38.67000741094249,
        'lng': -121.15421261828429,
        "fullAddress": "1024 E. Bidwell Street Folsom, CA 95630",
        "brand": "76",
        "storeBrand": "Power Market",
        "businessHours": "24/7",
        "email": "1005@hasoil.com",
        "address": "1024 E. Bidwell Street",
        "city": "Folsom",
        "state": "CA",
        "county": "Sacramento",
        "zip": "95630",
        "phone": "(916) 244-0081",
        "diesel": "",
        "dieselType": "",
        "es8": "",
        "alcohol": "",
        "deli": "",
        "fee-osp": "",
        "carwash": "Drive Thru",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage & Bulk",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "1006",
        'lat': 38.65796391060634,
        'lng': -120.96832773177738,
        "fullAddress": "4051 Cameron Park Dr Cameron Park, CA 95682",
        "brand": "76",
        "storeBrand": "Power Market",
        "businessHours": "24/7",
        "email": "1006@hasoil.com",
        "address": "4051 Cameron Park Dr",
        "city": "Cameron Park",
        "state": "CA",
        "county": "El Dorado",
        "zip": "95682",
        "phone": "(530) 285-5470",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "",
        "deli": "",
        "fee-osp": "",
        "carwash": "Drive Thru",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Bulk",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "1007",
        'lat': 39.328061049734956,
        'lng': -120.18450116058962,
        "fullAddress": "10041 Donner Pass Rd Truckee , CA 96161",
        "brand": "76",
        "storeBrand": "Power Market",
        "businessHours": "5:30am- 11:00pm",
        "email": "1007@hasoil.com",
        "address": "10041 Donner Pass Rd",
        "city": "Truckee ",
        "state": "CA",
        "county": "Nevada",
        "zip": "96161",
        "phone": "(530) 285-5471",
        "diesel": "",
        "dieselType": "",
        "es8": "",
        "alcohol": "",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "1008",
        'lat': 39.2509179445515,
        'lng': -119.96224398757758,
        "fullAddress": "790 Tahoe Blvd. Incline Village, NV 89450",
        "brand": "76",
        "storeBrand": "Power Market",
        "businessHours": "5:00am- 12:00pm",
        "email": "1008@hasoil.com",
        "address": "790 Tahoe Blvd.",
        "city": "Incline Village",
        "state": "NV",
        "county": "Washoe",
        "zip": "89450",
        "phone": "(775) 218 -3300 ",
        "diesel": "",
        "dieselType": "",
        "es8": "",
        "alcohol": "",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "1009",
        'lat': 33.85813319050386,
        'lng': -118.09917933193422,
        "fullAddress": "11004 South St, Cerritos, Ca 90703",
        "brand": "Shell",
        "storeBrand": "Power Market",
        "businessHours": "24/7",
        "email": "1009@hasoil.com",
        "address": "11004 South St",
        "city": " Cerritos",
        "state": "CA",
        "county": "Los Angeles",
        "zip": "90703",
        "phone": "(562) 267-3933",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "Yes",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "",
        "propane": "",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "1010",
        'lat': 38.95659653263764,
        'lng': -121.1008489894385,
        "fullAddress": "3960 Grass Valley HWY . Auburn , CA 95602",
        "brand": "76",
        "storeBrand": "Power Market",
        "businessHours": "24/7",
        "email": "1010@hasoil.com",
        "address": "3960 Grass Valley hwy",
        "city": "Auburn ",
        "state": "CA",
        "county": "Placer",
        "zip": "95602",
        "phone": "(530) 287-0555",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "",
        "deli": "",
        "fee-osp": "",
        "carwash": "Drive Thru",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "1011",
        'lat': 38.51045504879,
        'lng': -121.37099297411088,
        "fullAddress": "8908 Elder Creek Road Sacramento CA 95828",
        "brand": "H&S",
        "storeBrand": "Power Market",
        "businessHours": "24/7",
        "email": "1011@hasoil.com",
        "address": "8908 Elder Creek Road",
        "city": "Sacramento ",
        "state": "CA",
        "county": "Sacramento ",
        "zip": "95828",
        "phone": "(916) 550-3033",
        "diesel": "",
        "dieselType": "",
        "es8": "",
        "alcohol": "",
        "deli": "",
        "fee-osp": "",
        "carwash": "Drive Thru",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "1033",
        'lat': 33.83979640039485,
        'lng': -117.88958371844222,
        "fullAddress": "201 S. State College Blvd. Anaheim, CA Orange 92806",
        "brand": "Shell",
        "storeBrand": "Power Market",
        "businessHours": "24/7",
        "email": "1033@hasoil.com",
        "address": "201 S. State College Blvd.",
        "city": "Anaheim",
        "state": "CA",
        "county": "Orange",
        "zip": "92806",
        "phone": "(714) 533-6661",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "",
        "deli": "",
        "fee-osp": "",
        "carwash": "Drive Thru",
        "serviceShop": "",
        "loyalty": "",
        "propane": "Bulk Propane",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "2003",
        'lat': 33.82449998414928,
        'lng': -118.02781594542789,
        "fullAddress": "9500 Valley View St. Cypress, CA Orange 90630",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "24/7",
        "email": "2003@hasoil.com",
        "address": "9500 Valley View St.",
        "city": "Cypress",
        "state": "CA",
        "county": "Orange",
        "zip": "90630",
        "phone": "(714) 821-8021",
        "diesel": "",
        "dieselType": "",
        "es8": "",
        "alcohol": "",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "2016",
        'lat': 33.80289329254803,
        'lng': -118.04392908775708,
        "fullAddress": "5100 Katella Ave. Los Alamitos, CA Orange 90720",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "24/7",
        "email": "2016@hasoil.com",
        "address": "5100 Katella Ave.",
        "city": "Los Alamitos",
        "state": "CA",
        "county": "Orange",
        "zip": "90720",
        "phone": "(562) 596-5667",
        "diesel": "",
        "dieselType": "",
        "es8": "",
        "alcohol": "",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "2017",
        'lat': 34.07750677602863,
        'lng': -117.69010518959907,
        "fullAddress": "9700 Central Ave. Montclair, CA San Bernardino 91763",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "24/7",
        "email": "2017@hasoil.com",
        "address": "9700 Central Ave.",
        "city": "Montclair",
        "state": "CA",
        "county": "San Bernardino",
        "zip": "91763",
        "phone": "(909) 625-8888",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "2036",
        'lat': 33.60382009880542,
        'lng': -117.87294446077779,
        "fullAddress": "2546 E. Coast Hwy. Corona Del Mar, Ca Orange 92625",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "24/7",
        "email": "2036@hasoil.com",
        "address": "2546 E. Coast Hwy.",
        "city": "Corona Del Mar",
        "state": "Ca",
        "county": "Orange",
        "zip": "92625",
        "phone": "(949) 717-5095",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "Yes",
        "alcohol": "",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "Yes",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "2037",
        'lat': 33.52613240805616,
        'lng': -117.71167833194428,
        "fullAddress": "30072 Crown Valley Pkwy. Laguna Niguel, CA Orange 92677",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "24/7",
        "email": "2037@hasoil.com",
        "address": "30072 Crown Valley Pkwy.",
        "city": "Laguna Niguel",
        "state": "CA",
        "county": "Orange",
        "zip": "92677",
        "phone": "(949) 495-0345",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "Yes",
        "alcohol": "",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "Yes",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "2052",
        'lat': 33.99812345393312,
        'lng': -117.65124153193,
        "fullAddress": "14088 Euclid Ave. Chino CA 91710 ",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "24/7",
        "email": "2052@hasoil.com",
        "address": "14088 Euclid Ave. ",
        "city": "Chino ",
        "state": "CA",
        "county": "San Bernardino",
        "zip": "91710",
        "phone": "(909) 858-3023 ",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "Yes",
        "deli": "",
        "fee-osp": "",
        "carwash": "Drive thru",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "2054",
        'lat': 34.97273892599473,
        'lng': -120.57151823189952,
        "fullAddress": "1080 Guadalupe Ave, Guadalupe, Ca 93434",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "24/7",
        "email": "2054@hasoil.com",
        "address": "1080 Guadalupe Ave",
        "city": " Guadalupe",
        "state": "CA",
        "county": "Santa Barbara",
        "zip": "93434",
        "phone": "(805) 250-7899",
        "diesel": "",
        "dieselType": "",
        "es8": "",
        "alcohol": "",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "",
        "propane": "",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "2057",
        'lat': 34.019603917030075,
        'lng': -118.49741031843662,
        "fullAddress": "432 Wilshire Blvd, Santa Monica, Ca 90401",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "24/7",
        "email": "2057@hasoil.com",
        "address": "432 Wilshire Blvd",
        "city": " Santa Monica",
        "state": "CA",
        "county": "Los Angeles",
        "zip": "90401",
        "phone": "(213) 336-4992",
        "diesel": "",
        "dieselType": "",
        "es8": "",
        "alcohol": "",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "",
        "propane": "",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "2058",
        'lat': 34.02391118392516,
        'lng': -118.48577403192908,
        "fullAddress": "1330 Santa Monica Blvd, Santa Monica, Ca 90404",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "24/7",
        "email": "2058@hasoil.com",
        "address": "1330 Santa Monica Blvd",
        "city": " Santa Monica",
        "state": "CA",
        "county": "Los Angeles",
        "zip": "90404",
        "phone": "(213) 336-4991",
        "diesel": "",
        "dieselType": "",
        "es8": "",
        "alcohol": "",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "",
        "propane": "",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "2059",
        'lat': 34.01431762866138,
        'lng': -118.48564593192943,
        "fullAddress": "1732 Lincoln Blvd, Santa Monica, Ca 90404",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "24/7",
        "email": "2059@hasoil.com",
        "address": "1732 Lincoln Blvd",
        "city": " Santa Monica",
        "state": "CA",
        "county": "Los Angeles",
        "zip": "90404",
        "phone": "(213) 336-4990",
        "diesel": "",
        "dieselType": "",
        "es8": "",
        "alcohol": "",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "",
        "propane": "",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "2060",
        'lat': 34.05263315520883,
        'lng': -118.46954697425669,
        "fullAddress": "11852 San Vicente Blvd, La, Ca 90049",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "24/7",
        "email": "2060@hasoil.com",
        "address": "11852 San Vicente Blvd",
        "city": " La",
        "state": "CA",
        "county": "Los Angeles",
        "zip": "90049",
        "phone": "(213) 336-4989",
        "diesel": "",
        "dieselType": "",
        "es8": "",
        "alcohol": "",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "",
        "propane": "",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "2061",
        'lat': 34.001585745593346,
        'lng': -118.46842063192993,
        "fullAddress": "251 Lincoln Blvd, Venice Ca, Ca 90291",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "24/7",
        "email": "2061@hasoil.com",
        "address": "251 Lincoln Blvd",
        "city": " Venice Ca",
        "state": "CA",
        "county": "Los Angeles",
        "zip": "90291",
        "phone": "(213) 336-4987",
        "diesel": "",
        "dieselType": "",
        "es8": "",
        "alcohol": "",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "",
        "propane": "",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "2063",
        'lat': 34.00256604323177,
        'lng': -118.41249671843717,
        "fullAddress": "11305 Culver Blvd, La, Ca 90066",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "24/7",
        "email": "2063@hasoil.com",
        "address": "11305 Culver Blvd",
        "city": " La",
        "state": "CA",
        "county": "Los Angeles",
        "zip": "90066",
        "phone": "(213) 336-4984",
        "diesel": "",
        "dieselType": "",
        "es8": "",
        "alcohol": "",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "",
        "propane": "",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "2064",
        'lat': 34.03390269448534,
        'lng': -118.26215750124251,
        "fullAddress": "1516 S. Main St, La, Ca 90015",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "24/7",
        "email": "2064@hasoil.com",
        "address": "1516 S. Main St",
        "city": " La",
        "state": "CA",
        "county": "Los Angeles",
        "zip": "90015",
        "phone": "(213) 336-4983",
        "diesel": "",
        "dieselType": "",
        "es8": "",
        "alcohol": "",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "",
        "propane": "",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "2065",
        'lat': 33.53992355100629,
        'lng': -117.78102258961539,
        "fullAddress": "604 S. Coast Hwy, Laguan Beach, Ca 92651",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "24/7",
        "email": "2065@hasoil.com",
        "address": "604 S. Coast Hwy",
        "city": " Laguan Beach",
        "state": "CA",
        "county": "Orange",
        "zip": "92651",
        "phone": "(949) 303-7130",
        "diesel": "",
        "dieselType": "",
        "es8": "",
        "alcohol": "",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "",
        "propane": "",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3001",
        'lat': 38.387006322541396,
        'lng': -122.7140905164436,
        "fullAddress": "3825 Santa Rosa Ave. Santa Rosa, CA Sonoma 95407",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "4:30AM - 11:00PM",
        "email": "3001@hasoil.com",
        "address": "3825 Santa Rosa Ave.",
        "city": "Santa Rosa",
        "state": "CA",
        "county": "Sonoma",
        "zip": "95407",
        "phone": "(707) 585-9341",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "Yes",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3002",
        'lat': 38.43823097127354,
        'lng': -122.68712061644187,
        "fullAddress": "1300 Farmers Lane Santa Rosa, Ca Sonoma 95405",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "4:30AM - 11:00PM",
        "email": "3002@hasoil.com",
        "address": "1300 Farmers Lane",
        "city": "Santa Rosa",
        "state": "Ca",
        "county": "Sonoma",
        "zip": "95405",
        "phone": "(707) 575-9700",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "Yes",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3003",
        'lat': 39.043242422536494,
        'lng': -122.77575600292809,
        "fullAddress": "12589 E. Hwy 20 Clearlake Oaks, CA Lake 95423",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "4:30AM - 11:00PM",
        "email": "3003@hasoil.com",
        "address": "12589 E. Hwy 20",
        "city": "Clearlake Oaks",
        "state": "CA",
        "county": "Lake",
        "zip": "95423",
        "phone": "(707) 998-9316",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "Yes",
        "alcohol": "Yes",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3004",
        'lat': 38.911648023758815,
        'lng': -122.6125880740967,
        "fullAddress": "9815 Hwy 53 Lower Lake, CA Lake 95457",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "4:30AM - 11:00PM",
        "email": "3004@hasoil.com",
        "address": "9815 Hwy 53",
        "city": "Lower Lake",
        "state": "CA",
        "county": "Lake",
        "zip": "95457",
        "phone": "(707) 994-5846",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "Yes",
        "alcohol": "Yes",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3005",
        'lat': 39.07141563140391,
        'lng': -122.91457844525549,
        "fullAddress": "2935 Lakeshore Blvd. Lakeport, CA Lake 95453",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "4:30AM - 11:00PM",
        "email": "3005@hasoil.com",
        "address": "2935 Lakeshore Blvd.",
        "city": "Lakeport",
        "state": "CA",
        "county": "Lake",
        "zip": "95453",
        "phone": "(707) 263-7434",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "Yes",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3006",
        'lat': 39.08825085854251,
        'lng': -122.7937531894337,
        "fullAddress": "6282 Hwy 20 Lucerne, CA Lake 95458",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "4:30AM - 11:00PM",
        "email": "3006@hasoil.com",
        "address": "6282 Hwy 20",
        "city": "Lucerne",
        "state": "CA",
        "county": "Lake",
        "zip": "95458",
        "phone": "(707) 274-8196",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "Yes",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3007",
        'lat': 39.03321302091092,
        'lng': -122.92506763176424,
        "fullAddress": "1088 Lakeport Blvd. Lakeport, CA Lake 95453",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "4:30AM - 11:00PM",
        "email": "3007@hasoil.com",
        "address": "1088 Lakeport Blvd.",
        "city": "Lakeport",
        "state": "CA",
        "county": "Lake",
        "zip": "95453",
        "phone": "(707) 263-0870",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "Yes",
        "alcohol": "Yes",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3008",
        'lat': 39.041309897963075,
        'lng': -122.9149532875849,
        "fullAddress": "202 S. Main St. Lakeport, CA Lake 95453",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "5:00AM - 10:00PM",
        "email": "3008@hasoil.com",
        "address": "202 S. Main St.",
        "city": "Lakeport",
        "state": "CA",
        "county": "Lake",
        "zip": "95453",
        "phone": "(707) 263-7220",
        "diesel": "",
        "dieselType": "",
        "es8": "",
        "alcohol": "Yes",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3010",
        'lat': 40.56427278154642,
        'lng': -122.34020442985867,
        "fullAddress": "1670 Hartnell Ave. Redding, CA Shasta 96002",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "4:30AM - 11:30PM",
        "email": "3010@hasoil.com",
        "address": "1670 Hartnell Ave.",
        "city": "Redding",
        "state": "CA",
        "county": "Shasta",
        "zip": "96002",
        "phone": "(530) 222-2348",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "Yes",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3011",
        'lat': 40.626915084974556,
        'lng': -122.40459334705032,
        "fullAddress": "1495 Lake Blvd. Redding, CA Shasta 96003",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "4:30AM - 10:00PM",
        "email": "3011@hasoil.com",
        "address": "1495 Lake Blvd.",
        "city": "Redding",
        "state": "CA",
        "county": "Shasta",
        "zip": "96003",
        "phone": "(530) 241-4629",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "Yes",
        "deli": "Yes",
        "fee-osp": "",
        "carwash": "Drive Thru",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3012",
        'lat': 40.438140282286625,
        'lng': -122.29191554520649,
        "fullAddress": "1975 Ponderosa Way Anderson, CA Shasta 96007",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "5:00AM - 10:30PM",
        "email": "3012@hasoil.com",
        "address": "1975 Ponderosa Way",
        "city": "Anderson",
        "state": "CA",
        "county": "Shasta",
        "zip": "96007",
        "phone": "(530) 365-0332",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "Yes",
        "alcohol": "Yes",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3013",
        'lat': 40.453846540961685,
        'lng': -122.30738411822064,
        "fullAddress": "3480 West Center St. Anderson, CA Shasta 96007",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "5:00AM - 10:30PM",
        "email": "3013@hasoil.com",
        "address": "3480 West Center St.",
        "city": "Anderson",
        "state": "CA",
        "county": "Shasta",
        "zip": "96007",
        "phone": "(530) 365-5357",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "Yes",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3014",
        'lat': 39.767443545659226,
        'lng': -121.85638377406654,
        "fullAddress": "710 E. Lassen Ave. Chico, CA Butte 95973",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "4:30AM - 11:30PM",
        "email": "3014@hasoil.com",
        "address": "710 E. Lassen Ave.",
        "city": "Chico",
        "state": "CA",
        "county": "Butte",
        "zip": "95973",
        "phone": "(530) 892-2812",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "Yes",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3015",
        'lat': 39.74259956377738,
        'lng': -121.88253118941056,
        "fullAddress": "1255 W. East Ave. Chico, CA Butte 95926",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "4:30AM - 10:30PM",
        "email": "3015@hasoil.com",
        "address": "1255 W. East Ave.",
        "city": "Chico",
        "state": "CA",
        "county": "Butte",
        "zip": "95926",
        "phone": "(530) 892-2793",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "Yes",
        "alcohol": "Yes",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3016",
        'lat': 39.71496745513991,
        'lng': -121.81274136057583,
        "fullAddress": "110 E. Park Ave. Chico, CA Butte 95926",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "4:30AM - 10:30PM",
        "email": "3016@hasoil.com",
        "address": "110 E. Park Ave.",
        "city": "Chico",
        "state": "CA",
        "county": "Butte",
        "zip": "95926",
        "phone": "(530) 345-4265",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "Yes",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3017",
        'lat': 39.502752929553516,
        'lng': -121.53928075873277,
        "fullAddress": "2970 Olive Hwy. Oroville, CA Butte 95966",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "4:30AM - 10:30PM",
        "email": "3017@hasoil.com",
        "address": "2970 Olive Hwy.",
        "city": "Oroville",
        "state": "CA",
        "county": "Butte",
        "zip": "95966",
        "phone": "(530) 534-3081",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "Yes",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3020",
        'lat': 38.89813241882777,
        'lng': -121.32319871827619,
        "fullAddress": "2330 Nicolaus Rd. Lincoln, CA Placer 95648",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "4:30AM - 11:00PM",
        "email": "3020@hasoil.com",
        "address": "2330 Nicolaus Rd.",
        "city": "Lincoln",
        "state": "CA",
        "county": "Placer",
        "zip": "95648",
        "phone": "(916) 543-2176",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "Yes",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": "Torso"
      },
      {
        "storeId": "3023",
        'lat': 38.81445692550649,
        'lng': -121.2866424029361,
        "fullAddress": "1050 Sunset Blvd. Rocklin, CA Placer 95765",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "4:30AM - 11:00PM",
        "email": "3023@hasoil.com",
        "address": "1050 Sunset Blvd.",
        "city": "Rocklin",
        "state": "CA",
        "county": "Placer",
        "zip": "95765",
        "phone": "(916) 435-8465",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "Yes",
        "deli": "Yes",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": "Courthouse"
      },
      {
        "storeId": "3024",
        'lat': 39.27437269163977,
        'lng': -121.66044873175579,
        "fullAddress": "9811 Live Oak Blvd.  , CA Sutter 95953",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "4:30AM - 11:30PM",
        "email": "3024@hasoil.com",
        "address": "9811 Live Oak Blvd.",
        "city": "Live Oak",
        "state": "CA",
        "county": "Sutter",
        "zip": "95953",
        "phone": "(530) 695-0585",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "Yes",
        "deli": "Yes",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3025",
        'lat': 39.07700780528976,
        'lng': -121.54371027594155,
        "fullAddress": "1976 McGowan Pkwy. Olivehurst, CA Yuba 95961",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "4:30AM - 11:00PM",
        "email": "3025@hasoil.com",
        "address": "1976 McGowan Pkwy.",
        "city": "Olivehurst",
        "state": "CA",
        "county": "Yuba",
        "zip": "95961",
        "phone": "(530) 743-1810",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "Yes",
        "alcohol": "Yes",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3026",
        'lat': 39.07677957704526,
        'lng': -121.56069337409103,
        "fullAddress": "4217 Arboga Rd. Olivehurst, CA Yuba 95961",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "4:30AM - 11:00PM",
        "email": "3026@hasoil.com",
        "address": "4217 Arboga Rd.",
        "city": "Olivehurst",
        "state": "CA",
        "county": "Yuba",
        "zip": "95961",
        "phone": "(530) 749-9600",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "Yes",
        "deli": "Yes",
        "fee-osp": "",
        "carwash": "Drive Thru",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3027",
        'lat': 38.668290685234446,
        'lng': -121.76520216061277,
        "fullAddress": "901 East St. Woodland, CA Yolo 95695",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "4:30AM - 11:00PM",
        "email": "3027@hasoil.com",
        "address": "901 East St.",
        "city": "Woodland",
        "state": "CA",
        "county": "Yolo",
        "zip": "95695",
        "phone": "(530) 668-8164",
        "diesel": "",
        "dieselType": "",
        "es8": "Yes",
        "alcohol": "Yes",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3028",
        'lat': 38.64843522984488,
        'lng': -121.35957566246394,
        "fullAddress": "4430 Auburn Blvd. Sacramento, CA Sacramento 95841",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "4:30AM - 11:00PM",
        "email": "3028@hasoil.com",
        "address": "4430 Auburn Blvd.",
        "city": "Sacramento",
        "state": "CA",
        "county": "Sacramento",
        "zip": "95841",
        "phone": "(916) 484-9710",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "Yes",
        "deli": "Yes",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3029",
        'lat': 39.10023999280611,
        'lng': -121.61730606059766,
        "fullAddress": "530 Bogue Rd. Yuba City, CA Sutter 95991",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "4:30AM - 11:00PM",
        "email": "3029@hasoil.com",
        "address": "530 Bogue Rd.",
        "city": "Yuba City",
        "state": "CA",
        "county": "Sutter",
        "zip": "95991",
        "phone": "(530) 671-3999",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "Yes",
        "deli": "Yes",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3032",
        'lat': 38.68900348549471,
        'lng': -120.83124124526893,
        "fullAddress": "130 Pleasant Vly Rd. Diamond Springs, CA El Dorado 95619",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "4:30AM - 11:00PM",
        "email": "3032@hasoil.com",
        "address": "130 Pleasant Vly Rd.",
        "city": "Diamond Springs",
        "state": "CA",
        "county": "El Dorado",
        "zip": "95619",
        "phone": "(530) 621-1895",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "Yes",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3033",
        'lat': 38.07595128560233,
        'lng': -120.5474598183047,
        "fullAddress": "1049 South Main St. Angels Camp, CA Calaveras 95222",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "5:00AM - 9:00PM",
        "email": "3033@hasoil.com",
        "address": "1049 South Main St.",
        "city": "Angels Camp",
        "state": "CA",
        "county": "Calaveras",
        "zip": "95222",
        "phone": "(209) 736-9469",
        "diesel": "",
        "dieselType": "",
        "es8": "",
        "alcohol": "Yes",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3034",
        'lat': 37.79713872761516,
        'lng': -121.23906321646375,
        "fullAddress": "1434 W. Yosemite Ave. Manteca, CA San Joaquin 95337",
        "brand": "Texaco",
        "storeBrand": "Power Market",
        "businessHours": "5:00AM - 11:00PM",
        "email": "3034@hasoil.com",
        "address": "1434 W. Yosemite Ave.",
        "city": "Manteca",
        "state": "CA",
        "county": "San Joaquin",
        "zip": "95337",
        "phone": "(209) 823-2057",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "Yes",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3035",
        'lat': 37.82600968894835,
        'lng': -121.28608919159747,
        "fullAddress": "192 Lathrop Rd. Lathrop, CA San Joaquin 95330",
        "brand": "H&S",
        "storeBrand": "Power Market",
        "businessHours": "24/7",
        "email": "3035@hasoil.com",
        "address": "192 Lathrop Rd.",
        "city": "Lathrop",
        "state": "CA",
        "county": "San Joaquin",
        "zip": "95330",
        "phone": "(209) 858-4998",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "Yes",
        "alcohol": "Yes",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3036",
        'lat': 38.199963730111385,
        'lng': -120.68873892994264,
        "fullAddress": "440 W. St. Charles St. San Andreas, CA Calaveras 95249",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "24/7",
        "email": "3036@hasoil.com",
        "address": "440 W. St. Charles St.",
        "city": "San Andreas",
        "state": "CA",
        "county": "Calaveras",
        "zip": "95249",
        "phone": "(209) 754-1478",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "Yes",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Yes",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3040",
        'lat': 37.997827494164696,
        'lng': -121.71426721830758,
        "fullAddress": "3475 Main St. Oakley, CA Contra Costa 94561",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "4:30AM - 11:00PM",
        "email": "3040@hasoil.com",
        "address": "3475 Main St.",
        "city": "Oakley",
        "state": "CA",
        "county": "Contra Costa",
        "zip": "94561",
        "phone": "(925) 625-3602",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "Yes",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3041",
        'lat': 38.53981978417259,
        'lng': -121.55092791643816,
        "fullAddress": "3180 Jefferson Blvd. West Sacramento, CA Yolo 95691",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "4:30AM - 11:00PM",
        "email": "3041@hasoil.com",
        "address": "3180 Jefferson Blvd.",
        "city": "West Sacramento",
        "state": "CA",
        "county": "Yolo",
        "zip": "95691",
        "phone": "(916) 371-1422",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "Yes",
        "deli": "Yes",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": "Quota"
      },
      {
        "storeId": "3042",
        'lat': 38.18221345602812,
        'lng': -122.1377269164507,
        "fullAddress": "4720 Gold Hill Rd. Fairfield, CA Solano 94534",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "4:30AM - 11:00PM",
        "email": "3042@hasoil.com",
        "address": "4720 Gold Hill Rd.",
        "city": "Fairfield",
        "state": "CA",
        "county": "Solano",
        "zip": "94534",
        "phone": "(707) 864-2506",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "Yes",
        "alcohol": "Yes",
        "deli": "Yes",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3043",
        'lat': 38.20324367701881,
        'lng': -122.15793804528573,
        "fullAddress": "119 Red Top Rd. Fairfield, CA Solano 94534",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "24/7",
        "email": "3043@hasoil.com",
        "address": "119 Red Top Rd.",
        "city": "Fairfield",
        "state": "CA",
        "county": "Solano",
        "zip": "94534",
        "phone": "(707) 863-0421",
        "diesel": "",
        "dieselType": "",
        "es8": "",
        "alcohol": "Yes",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": "Typewriter"
      },
      {
        "storeId": "3044",
        'lat': 37.9967143975011,
        'lng': -122.12008900296439,
        "fullAddress": "3012 Howe Rd. Martinez, CA Contra Costa 94553",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "4:30AM - 11:00PM",
        "email": "3044@hasoil.com",
        "address": "3012 Howe Rd.",
        "city": "Martinez",
        "state": "CA",
        "county": "Contra Costa",
        "zip": "94553",
        "phone": "(925) 372-7135",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "Yes",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": "Copyright"
      },
      {
        "storeId": "3045",
        'lat': 38.02656600519558,
        'lng': -121.95802100296338,
        "fullAddress": "3575 Willow Pass Rd. Bay Point, CA Contra Costa 94565",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "4:30AM - 11:00PM",
        "email": "3045@hasoil.com",
        "address": "3575 Willow Pass Rd.",
        "city": "Bay Point",
        "state": "CA",
        "county": "Contra Costa",
        "zip": "94565",
        "phone": "(925) 458-3894",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "Yes",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3046",
        'lat': 37.92537540034613,
        'lng': -121.68926248762364,
        "fullAddress": "8750 Brentwood Blvd. Brentwood, CA Contra Costa 94513",
        "brand": "H&S",
        "storeBrand": "Power Market",
        "businessHours": "4:30AM - 11:00PM",
        "email": "3046@hasoil.com",
        "address": "8750 Brentwood Blvd.",
        "city": "Brentwood",
        "state": "CA",
        "county": "Contra Costa",
        "zip": "94513",
        "phone": "(925) 516-7528",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "Yes",
        "alcohol": "Yes",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3047",
        'lat': 38.02673045611976,
        'lng': -121.92794591645605,
        "fullAddress": "1805 Willow Pass Rd. Bay Point, CA Contra Costa 94565",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "4:30AM - 11:00PM",
        "email": "3047@hasoil.com",
        "address": "1805 Willow Pass Rd.",
        "city": "Bay Point",
        "state": "CA",
        "county": "Contra Costa",
        "zip": "94565",
        "phone": "(925) 458-2689",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "Yes",
        "alcohol": "Yes",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": "Not installed yet "
      },
      {
        "storeId": "3048",
        'lat': 38.243775576067414,
        'lng': -122.12274157412,
        "fullAddress": "4155 Suisun Vly Rd. Suisun City, CA Solano 94534",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "4:30AM - 11:00PM",
        "email": "3048@hasoil.com",
        "address": "4155 Suisun Vly Rd.",
        "city": "Suisun City",
        "state": "CA",
        "county": "Solano",
        "zip": "94534",
        "phone": "(707) 864-1608",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "Yes",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3049",
        'lat': 38.02085717717415,
        'lng': -121.94216895878452,
        "fullAddress": "254 Bailey Rd. Pittsburg, CA Contra Costa 94565",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "4:30AM - 11:00PM",
        "email": "3049@hasoil.com",
        "address": "254 Bailey Rd.",
        "city": "Pittsburg",
        "state": "CA",
        "county": "Contra Costa",
        "zip": "94565",
        "phone": "(925) 458-4317",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "Yes",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3050",
        'lat': 38.093948431256024,
        'lng': -122.22855067412533,
        "fullAddress": "425 Laurel St. Vallejo, CA Solano 94591",
        "brand": "Texaco",
        "storeBrand": "Power Market",
        "businessHours": "5:30AM - 11:00PM",
        "email": "3050@hasoil.com",
        "address": "425 Laurel St.",
        "city": "Vallejo",
        "state": "CA",
        "county": "Solano",
        "zip": "94591",
        "phone": "(707) 557-0450",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "Yes",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3051",
        'lat': 38.66915292963633,
        'lng': -121.38202646061282,
        "fullAddress": "3519 A St. North Highlands, CA Sacramento 95660",
        "brand": "Texaco",
        "storeBrand": "Power Market",
        "businessHours": "4:30AM - 11:00PM",
        "email": "3051@hasoil.com",
        "address": "3519 A St.",
        "city": "North Highlands",
        "state": "CA",
        "county": "Sacramento",
        "zip": "95660",
        "phone": "(916) 332-9740",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "Yes",
        "alcohol": "Yes",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "Yes",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3053",
        'lat': 37.3096307073975,
        'lng': -121.88630228764444,
        "fullAddress": "545 West Alma Street San Jose, CA Santa Clara 95125",
        "brand": "Texaco",
        "storeBrand": "Power Market",
        "businessHours": "24/7",
        "email": "3053@hasoil.com",
        "address": "545 West Alma Street",
        "city": "San Jose",
        "state": "CA",
        "county": "Santa Clara",
        "zip": "95125",
        "phone": "(408) 547-1988",
        "diesel": "",
        "dieselType": "",
        "es8": "Yes",
        "alcohol": "",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3054",
        'lat': 37.33839193555038,
        'lng': -121.993350789494,
        "fullAddress": "3501 Homestead Rd Santa Clara, CA Santa Clara 95051",
        "brand": "Texaco",
        "storeBrand": "Power Market",
        "businessHours": "24/7",
        "email": "3054@hasoil.com",
        "address": "3501 Homestead Rd",
        "city": "Santa Clara",
        "state": "CA",
        "county": "Santa Clara",
        "zip": "95051",
        "phone": "(669) 600-0933",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3057",
        'lat': 37.59872388154555,
        'lng': -122.06613407414218,
        "fullAddress": "31300 Alvarado Niles Rd Union City, CA Alameda 94587",
        "brand": "Chevron ",
        "storeBrand": "Power Market",
        "businessHours": "24/7",
        "email": "3057@hasoil.com",
        "address": "31300 Alvarado Niles Rd",
        "city": "Union City",
        "state": "CA",
        "county": "Alameda",
        "zip": "94587",
        "phone": "(510) 588-1005",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3059",
        'lat': 37.56077728327218,
        'lng': -122.01243371647178,
        "fullAddress": "36979 Fremont Blvd. Fremont, CA Alameda 94536",
        "brand": "Texaco",
        "storeBrand": "Power Market",
        "businessHours": "24/7",
        "email": "3059@hasoil.com",
        "address": "36979 Fremont Blvd.",
        "city": "Fremont",
        "state": "CA",
        "county": "Alameda",
        "zip": "94536",
        "phone": "(510) 588-1010",
        "diesel": "",
        "dieselType": "",
        "es8": "",
        "alcohol": "",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3061",
        'lat': 37.74275146835526,
        'lng': -122.3885286183162,
        "fullAddress": "3800 3rd Street San Francisco, CA San Francisco 94124",
        "brand": "Texaco",
        "storeBrand": "Power Market",
        "businessHours": "24/7",
        "email": "3061@hasoil.com",
        "address": "3800 3rd Street",
        "city": "San Francisco",
        "state": "CA",
        "county": "San Francisco",
        "zip": "94124",
        "phone": "(415) 707-1330",
        "diesel": "",
        "dieselType": "",
        "es8": "",
        "alcohol": "",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3063",
        'lat': 39.32297846391381,
        'lng': -120.2268762164107,
        "fullAddress": "12353 Deerfield Dr Truckee, CA 96161",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "6:00am- 12:00am",
        "email": "3063@hasoil.com",
        "address": "12353 Deerfield Dr",
        "city": "Truckee",
        "state": "CA",
        "county": "Nevada",
        "zip": "96161",
        "phone": "(530) 285-5460",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3064",
        'lat': 38.856036622966315,
        'lng': -120.01407831642726,
        "fullAddress": "2986 US Hwy 50 South Lake Tahoe, CA 96150",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "6:00am- 9:00pm ",
        "email": "3064@hasoil.com",
        "address": "2986 US Hwy 50",
        "city": "South Lake Tahoe",
        "state": "CA",
        "county": "El Dorado",
        "zip": "96150",
        "phone": "(530) 285-5461",
        "diesel": "",
        "dieselType": "",
        "es8": "",
        "alcohol": "",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Bulk",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3065",
        'lat': 39.04166809597982,
        'lng': -121.09402337409232,
        "fullAddress": "10021 Combie Rd Auburn, CA 95602",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "24/7",
        "email": "3065@hasoil.com",
        "address": "10021 Combie Rd",
        "city": "Auburn",
        "state": "CA",
        "county": "Nevada",
        "zip": "95602",
        "phone": "(530) 285-5462",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "",
        "deli": "",
        "fee-osp": "",
        "carwash": "Drive Thru",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3067",
        'lat': 38.744554037255796,
        'lng': -121.3081888722522,
        "fullAddress": "3001 Foothills Blvd Roseville, CA 95678",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "24/7",
        "email": "3067@hasoil.com",
        "address": "3001 Foothills Blvd",
        "city": "Roseville",
        "state": "CA",
        "county": "Placer",
        "zip": "95678",
        "phone": "(916) 244-0083",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "",
        "deli": "",
        "fee-osp": "",
        "carwash": "Drive Thru",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3068",
        'lat': 38.713859144181974,
        'lng': -121.3640453894469,
        "fullAddress": "7966 Walerga Rd Antelope, CA 95843",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "24/7",
        "email": "3068@hasoil.com",
        "address": "7966 Walerga Rd",
        "city": "Antelope",
        "state": "CA",
        "county": "Sacramento",
        "zip": "95843",
        "phone": "(916) 244-0084",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "",
        "deli": "",
        "fee-osp": "",
        "carwash": "Drive Thru",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage & Bulk",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3069",
        'lat': 38.66365292878626,
        'lng': -121.27282697595614,
        "fullAddress": "5361 Sunrise Ave Fair Oaks, CA 95628",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "24/7",
        "email": "3069@hasoil.com",
        "address": "5361 Sunrise Ave",
        "city": "Fair Oaks",
        "state": "CA",
        "county": "Sacramento",
        "zip": "95628",
        "phone": "(916) 244-0085",
        "diesel": "",
        "dieselType": "",
        "es8": "",
        "alcohol": "",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3074",
        'lat': 38.61792155355431,
        'lng': -121.3464228317787,
        "fullAddress": "5049 Marconi Ave Carmichael, CA 95608",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "24/7",
        "email": "3074@hasoil.com",
        "address": "5049 Marconi Ave",
        "city": "Carmichael",
        "state": "CA",
        "county": "Sacramento",
        "zip": "95608",
        "phone": "(916) 244-0089",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "",
        "deli": "",
        "fee-osp": "",
        "carwash": "Drive Thru",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Bulk",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3075",
        'lat': 38.59619718860241,
        'lng': -121.36505133177955,
        "fullAddress": "4231 Arden Way Sacramento, CA 95864",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "6:00am- 12:00am",
        "email": "3075@hasoil.com",
        "address": "4231 Arden Way",
        "city": "Sacramento",
        "state": "CA",
        "county": "Sacramento",
        "zip": "95864",
        "phone": "(916) 244-0090",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "PM Loyalty",
        "propane": "Cage",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3084",
        'lat': 37.765555888591535,
        'lng': -121.43458360112164,
        "fullAddress": "3940 N. Tracy Blvd. Tracy CA 95304",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "24/7",
        "email": "3084@hasoil.com",
        "address": "3940 N. Tracy Blvd.",
        "city": "Tracy",
        "state": "CA",
        "county": "San Joaquin County",
        "zip": "95304",
        "phone": "(209) 879-0084",
        "diesel": "ULS",
        "dieselType": "",
        "es8": "",
        "alcohol": "",
        "deli": "",
        "fee-osp": "",
        "carwash": "",
        "serviceShop": "",
        "loyalty": "",
        "propane": "",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      },
      {
        "storeId": "3086",
        'lat': 37.452342150432024,
        'lng': -121.92123374531131,
        "fullAddress": "1551 California Circle Milpitas CA 95035",
        "brand": "Chevron",
        "storeBrand": "Power Market",
        "businessHours": "24/7",
        "email": "3086@hasoil.com",
        "address": "1551 California Circle",
        "city": "Milpitas",
        "state": "CA",
        "county": "Santa Clara County",
        "zip": "95035",
        "phone": "(408) 935-9752",
        "diesel": "",
        "dieselType": "",
        "es8": "",
        "alcohol": "",
        "deli": "",
        "fee-osp": "",
        "carwash": "Drive Thru",
        "serviceShop": "",
        "loyalty": "",
        "propane": "",
        "ebt": "",
        "wic": "",
        "deliveryService": "Power Market Delivery",
        "amazonLocker": ""
      }
    ]
  // 'features': [
  //   {
  //     'type': 'Feature',
  //     'lat': 33.9979233,
  //     'lng': -117.6538057,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '14088 Euclid Ave',
  //       'city': 'Chino',
  //       'open': '24/7',
  //       'storeId': 'PM #2052',
  //       'products': ['diesel']
  //     }
  //   },
  //   {
  //     'type': 'Feature',
  //     'lat': 34.0773157,
  //     'lng': -117.6926479,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '9700 Central Ave',
  //       'city': 'Montclair',
  //       'open': '24/7',
  //       'storeId': 'PM Go #2052',

  //     }
  //   },
  //   {
  //     'type': 'Feature',
  //     'lat': 33.5259669,
  //     'lng': -117.7142425,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '30072 Crown Valley Pkwy',
  //       'city': 'Laguna Niguel',
  //       'storeId': 'PM GO #2037',
  //       'open': '24/7',
  //       'amenities': ['service'],
  //       'products': ['propane', 'diesel', 'e58']
  //     }
  //   },
  //   {
  //     'type': 'Feature',
  //     'lat': 33.8396226,
  //     'lng': -117.8921157,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '201 S State College Blvd',
  //       'city': 'Anaheim',
  //       "open": '24/7',
  //       'storeId': 'PM GO #1033',
  //       'amenities': ['carwash'],
  //       'products': ['propane', 'e58']
  //     }
  //   },
  //   {
  //     'type': 'Feature',
  //     'lat': 33.603619,
  //     'lng': -117.8754979,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '2546 East Coast Hwy',
  //       'city': 'Corona Del Mar',
  //       'storeId': 'PM GO #2036',
  //       "open": '24/7',
  //       'amenities': ['service', 'carwash',],
  //       'products': ['propane', 'diesel', 'e58']
  //     }
  //   },
  //   {
  //     'type': 'Feature',
  //     'lat': 33.8242905,
  //     'lng': -118.0304123,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '9500 Valley View St',
  //       'city': 'Cypress',
  //       'country': 'United States',
  //       'storeId': 'PM GO #2003',
  //       "open": '24/7',
  //       'products': ['propane', 'alcohol']
  //     }
  //   },
  //   {
  //     'type': 'Feature',
  //     'lat': 39.274224,
  //     'lng': -121.660445,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '9500 Valley View St',
  //       'city': 'Montclair',
  //       'crossStreet': '9500 Valley View St',
  //       'storeId': 'PM #3024',
  //       "open": '4:30AM - 11:00PM',
  //       'products': ['propane', 'alcohol', 'diesel']
  //     }
  //   },

  //   {
  //     'type': 'Feature',
  //     'lat': 38.855909,
  //     'lng': -120.014121,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '2986 US Hwy 50 South',
  //       'city': 'lake Tahoe',
  //       'storeId': 'PM #3064',
  //       "open": '6:00AM - 9:00PM',
  //       'products': ['propane']
  //     }
  //   },

  //   {
  //     'type': 'Feature',
  //     'lat': 39.322809,
  //     'lng': -120.226901,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '12353 Deerfield Dr',
  //       'city': 'Truckee',
  //       'storeId': 'PM #3063',
  //       "open": '6:00AM - 12:00AM',
  //       'products': ['propane',]
  //     }
  //   },


  //   {
  //     'type': 'Feature',
  //     'lat': 38.072301,
  //     'lng': -120.541919,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '1049 South Main St',
  //       'city': 'Angels Camp CA 95222',
  //       'storeId': 'PM #3033',
  //       "open": '5:00AM - 11:00PM',
  //       'products': ['propane', 'alcohol']
  //     }
  //   },


  //   {
  //     'type': 'Feature',
  //     'lat': 38.199921,
  //     'lng': -120.688771,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '40 W. St. Charles St',
  //       'city': 'San Andreas CA 95249',
  //       'storeId': 'PM #3036',
  //       "open": '24/7',
  //       'products': ['propane', 'alcohol', 'diesel']
  //     }
  //   },

  //   {
  //     'type': 'Feature',
  //     'lat': 38.689271,
  //     'lng': -120.831241,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '130 Pleasant Vly Rd',
  //       'city': 'Diamond Springs CA 95619',
  //       'storeId': 'PM #3032',
  //       "open": '4:30AM - 11:00PM',
  //       'products': ['propane', 'alcohol', 'diesel']
  //     }
  //   },

  //   {
  //     'type': 'Feature',
  //     'lat': 38.956554,
  //     'lng': -121.100881,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '3960 Grass Valley Hwy',
  //       'city': 'Auburn CA 95602',
  //       'storeId': 'PM #1010',
  //       "open": '24/7',
  //     }
  //   },


  //   {
  //     'type': 'Feature',
  //     'lat': 38.814448,
  //     'lng': -121.286631,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '1050 Sunset Blvd.',
  //       'city': 'Rocklin CA 95765',
  //       'storeId': 'PM #3023',
  //       "open": '4:30AM - 11:00PM',
  //       'amenities': ['amazonlocker'],
  //       'products': ['diesel']

  //     }
  //   },

  //   {
  //     'type': 'Feature',
  //     'lat': 37.796980,
  //     'lng': -121.239095,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '1434 W. Yosemite Ave',
  //       'city': 'Manteca CA 95337',
  //       'storeId': 'PM #3034',
  //       "open": '5:00AM - 11:00PM',
  //       'products': ['diesel']

  //     }
  //   },

  //   {
  //     'type': 'Feature',
  //     'lat': 38.897974,
  //     'lng': -121.323162,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '2330 Nicolaus rd.',
  //       'city': 'Lincoln CA 95648',
  //       'storeId': 'PM #3020',
  //       "open": '4:30AM - 11:00PM',
  //       'amenities': ['amazonlocker'],
  //       'products': ['propane', 'alcohol', 'diesel']
  //     }
  //   },


  //   {
  //     'type': 'Feature',
  //     'lat': 37.826078,
  //     'lng': -121.286067,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '192 Lathrop Rd',
  //       'city': 'Lathrop CA 95330',
  //       'storeId': 'PM #3035',
  //       "open": '4:30AM - 11:00PM',
  //       'products': ['diesel', 'e58']

  //     }
  //   },

  //   {
  //     'type': 'Feature',
  //     'lat': 38.648166,
  //     'lng': -121.359892,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '4430 Auburn Blvd.',
  //       'city': 'Sacramento CA 95841',
  //       'storeId': 'PM #3028',
  //       "open": '4:30AM - 11:00PM',
  //       'products': ['diesel']

  //     }
  //   },
  //   {
  //     'type': 'Feature',
  //     'lat': 38.669186,
  //     'lng': -121.382026,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '3519 A St',
  //       'city': 'North Highlands CA 95660',
  //       'storeId': 'PM #3051',
  //       "open": '4:30AM - 11:00PM',
  //       'products': ['propane', 'diesel', 'e58']
  //     }
  //   },

  //   {
  //     'type': 'Feature',
  //     'lat': 39.502719,
  //     'lng': -121.539302,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '2970 Olive Hwy',
  //       'city': 'Oroville CA 95966',
  //       'storeId': 'PM #3017',
  //       "open": '4:30AM - 11:00PM',
  //       'products': ['propane', 'alcohol', 'diesel']
  //     }
  //   },

  //   {
  //     'type': 'Feature',
  //     'lat': 39.077066,
  //     'lng': -121.543645,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '1976 McGowan Pkwy.',
  //       'city': 'Olivehurst CA 95961',
  //       'storeId': 'PM #3025',
  //       "open": '4:30AM - 11:00PM',
  //       'products': ['propane', 'diesel', 'e58']

  //     }
  //   },

  //   {
  //     'type': 'Feature',
  //     'lat': 39.076787905743835,
  //     'lng': -121.56071483233171,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '4217 Arboga Rd',
  //       'city': 'Olivehurst CA 95961',
  //       'storeId': 'PM #3026',
  //       "open": '4:30AM - 11:00PM',
  //       'products': ['propane', 'alcohol', 'diesel']
  //     }
  //   },

  //   {
  //     'type': 'Feature',
  //     'lat': 38.53986174319737,
  //     'lng': -121.55097083235536,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '3180 Jefferson Blvd',
  //       'city': 'West Sacramento CA 95691',
  //       'storeId': 'PM #3041',
  //       "open": '4:30AM - 11:00PM',
  //       'amenities': ['amazonlocker'],
  //       'products': ['diesel']

  //     }
  //   },

  //   {
  //     'type': 'Feature',
  //     'lat': 39.10023999268907,
  //     'lng': -121.61732751883906,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '530 Bogue Rd.',
  //       'city': 'Yuba City CA 95991',
  //       'storeId': 'PM #3029',
  //       "open": '4:30AM - 11:00PM',
  //       'products': ['propane', 'alcohol', 'diesel']
  //     }
  //   },


  //   {
  //     'type': 'Feature',
  //     'lat': 37.925366,
  //     'lng': -121.689262,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '8750 Brentwood Blvd',
  //       'city': 'Brentwood CA 94513',
  //       'storeId': 'PM #3046',
  //       "open": '4:30AM - 11:00PM',
  //       'products': ['propane', 'alcohol', 'diesel', 'e58']

  //     }
  //   },

  //   {
  //     'type': 'Feature',
  //     'lat': 38.66825717782613,
  //     'lng': -121.76513778816904,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '901 East St',
  //       'city': 'Woodland CA 95695',
  //       'storeId': 'PM #3027',
  //       "open": '4:30AM - 11:00PM',
  //       'products': ['propane', 'alcohol', 'diesel', 'e58']
  //     }
  //   },

  //   {
  //     'type': 'Feature',
  //     'lat': 39.718695225441664,
  //     'lng': -121.81323053070642,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '110 E. Park Ave',
  //       'city': 'Chico CA 95926',
  //       'storeId': 'PM #3016',
  //       "open": '4:30AM - 11:00PM',
  //       'products': ['propane', 'alcohol', 'diesel']
  //     }
  //   },


  //   {
  //     'type': 'Feature',
  //     'lat': 37.997827,
  //     'lng': -121.714224,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '3475 Main St',
  //       'city': 'Oakley CA 94561',
  //       'storeId': 'PM #3040',
  //       "open": '4:30AM - 11:00PM',
  //       'products': ['propane', 'alcohol', 'diesel']
  //     }
  //   },


  //   {
  //     'type': 'Feature',
  //     'lat': 39.76739406539116,
  //     'lng': -121.85637304579237,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '710 E. Lassen Ave.',
  //       'city': 'Chico CA 95973',
  //       'storeId': 'PM #3014',
  //       "open": '4:30AM - 11:00PM',
  //       'products': ['propane', 'alcohol', 'diesel']
  //     }
  //   },

  //   {
  //     'type': 'Feature',
  //     'lat': 39.742607813323175,
  //     'lng': -121.88242390161273,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '1255 W. East Ave',
  //       'city': 'Chico CA 95926',
  //       'storeId': 'PM #3015',
  //       "open": '4:30AM - 11:00PM',
  //       'products': ['propane', 'alcohol', 'diesel', 'e58']
  //     }
  //   },

  //   {
  //     'type': 'Feature',
  //     'lat': 38.026722004647596,
  //     'lng': -121.92794591703314,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '1805 Willow Pass Rd',
  //       'city': 'Bay Point CA 94565',
  //       'storeId': 'PM #3047',
  //       "open": '4:30AM - 11:00PM',
  //       'products': ['propane', 'alcohol', 'diesel', 'e58']
  //     }
  //   },
  //   {
  //     'type': 'Feature',
  //     'lat': 38.02082336891849,
  //     'lng': -121.94216895936117,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '254 Bailey Rd.',
  //       'city': 'Pittsburg CA 94565',
  //       'storeId': 'PM #3049',
  //       "open": '4:30AM - 11:00PM',
  //       'products': ['propane', 'alcohol', 'diesel']
  //     }
  //   },

  //   {
  //     'type': 'Feature',
  //     'lat': 38.02653219957386,
  //     'lng': -121.95807464772223,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '3575 Willow Pass Rd.',
  //       'city': 'Bay Point CA 94565',
  //       'storeId': 'PM #3045',
  //       "open": '4:30AM - 11:00PM',
  //       'products': ['propane', 'alcohol', 'diesel']
  //     }
  //   },

  //   {
  //     'type': 'Feature',
  //     'lat': 37.30965630751221,
  //     'lng': -121.88642059131067,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '545 West Alma Street ',
  //       'city': 'San Jose CA 95125',
  //       'storeId': 'PM GO #3053',
  //       "open": '24/7',
  //       'products': ['e58']
  //     }
  //   },


  //   {
  //     'type': 'Feature',
  //     'lat': 37.56077728315674,
  //     'lng': -122.01239080170865,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '36979 Fremont Blvd.',
  //       'city': 'Fremont CA 94536',
  //       'storeId': 'PM GO #3059',
  //       "open": '24/7',
  //       'products': ['propane',]
  //     }
  //   },

  //   {
  //     'type': 'Feature',
  //     'lat': 37.338417525868756,
  //     'lng': -121.99327568822659,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '3501 Homestead Rd',
  //       'city': 'Santa Clara CA 95051',
  //       'storeId': 'PM GO #3054',
  //       "open": '24/7',
  //       'products': ['propane', 'diesel']
  //     }
  //   },


  //   {
  //     'type': 'Feature',
  //     'lat': 38.243775575951204,
  //     'lng': -122.12275230353207,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '4155 Suisun Vly Rd',
  //       'city': 'Suisun City CA 94534',
  //       'storeId': 'PM #3048',
  //       "open": '4:30AM - 11:00PM',
  //       'products': ['alcohol', 'propane', 'diesel'],

  //     }
  //   },

  //   {
  //     'type': 'Feature',
  //     'lat': 37.598766383874406,
  //     'lng': -122.06619844774056,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '31300 Alvarado Niles Rd',
  //       'city': 'Union City CA 94587',
  //       'storeId': 'PM GO #3057',
  //       "open": '24/7',
  //       'products': ['diesel']
  //     }
  //   },

  //   {
  //     'type': 'Feature',
  //     'lat': 37.99667212328904,
  //     'lng': -122.1201855630681,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '3012 howe Rd.',
  //       'city': 'Martinez CA 94553',
  //       'storeId': 'PM #3044',
  //       "open": '4:30AM - 11:00PM',
  //       'amenities': ['amazonlocker'],
  //       'products': ['propane', 'alcohol', 'diesel',]

  //     }
  //   },

  //   {
  //     'type': 'Feature',
  //     'lat': 38.18223032268761,
  //     'lng': -122.13774837469866,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '4720 Gold Hill Rd.',
  //       'city': 'Fairfield CA 94534',
  //       'storeId': 'PM #3042',
  //       "open": '4:30AM - 11:00PM',
  //       'products': ['propane', 'alcohol', 'diesel', "e58"]
  //     }
  //   },

  //   {
  //     'type': 'Feature',
  //     'lat': 38.203176229239425,
  //     'lng': -122.15798096120615,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '119 Red Top Rd.',
  //       'city': 'Fairfield CA 94534',
  //       'storeId': 'PM #3043',
  //       "open": '24/7',
  //       'amenities': ['amazonlocker'],
  //       'products': ['propane', 'alcohol']
  //     }
  //   },

  //   {
  //     'type': 'Feature',
  //     'lat': 40.438132116379165,
  //     'lng': -122.2919691899425,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '1975 Ponderosa Way',
  //       'city': 'Anderson CA 96007',
  //       'storeId': 'PM #3012',
  //       "open": '4:30AM - 11:00PM',
  //       'products': ['propane', 'alcohol', 'e58']
  //     }
  //   },



  //   {
  //     'type': 'Feature',
  //     'lat': 40.453854704724,
  //     'lng': -122.30731974576099,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '3480 West Center St',
  //       'city': 'Anderson CA 96007',
  //       'storeId': 'PM #3013',
  //       "open": '4:30AM - 11:00PM',
  //       'products': ['propane', 'alcohol', 'diesel']

  //     }
  //   },

  //   {
  //     'type': 'Feature',
  //     'lat': 40.56425648052762,
  //     'lng': -122.34021515924763,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '1670 Hartnell Ave',
  //       'city': 'Redding CA 96002',
  //       'storeId': 'PM #3010',
  //       "open": '4:30AM - 11:00PM',
  //       'products': ['alcohol', 'propane', 'diesel']
  //     }
  //   },


  //   {
  //     'type': 'Feature',
  //     'lat': 38.0939484311399,
  //     'lng': -122.22859359004713,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '425 Laurel St.',
  //       'city': 'Vallejo CA 94591',
  //       'storeId': 'PM #3050',
  //       "open": '5:30AM - 11:00PM',
  //       'products': ['propane', 'alcohol', 'diesel',]
  //     }
  //   },

  //   {
  //     'type': 'Feature',
  //     'lat': 40.62682551381508,
  //     'lng': -122.4045504322616,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '1495 Lake Blvd',
  //       'city': 'Redding CA 96003',
  //       'storeId': 'PM #3011',
  //       "open": '4:30AM - 11:00PM',
  //       'amenities': ['carwash'],
  //       'products': ['propane', 'alcohol', 'diesel']


  //     }
  //   },

  //   {
  //     'type': 'Feature',
  //     'lat': 37.74307003635559,
  //     'lng': -122.3884322602122,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '3800 3rd Street',
  //       'city': 'San Francisco CA 94124',
  //       'storeId': 'PM GO #3061',
  //       "open": '24/7',
  //       'products': ['propane']
  //     }
  //   },

  //   {
  //     'type': 'Feature',
  //     'lat': 38.911622978817995,
  //     'lng': -122.61262026117512,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '9815 Hwy 53',
  //       'city': 'Lower Lake CA 95457',
  //       'storeId': 'PM #3004',
  //       "open": '4:30AM - 11:00PM',
  //       'products': ['propane', 'alcohol', 'diesel', 'e58']
  //     }
  //   },


  //   {
  //     'type': 'Feature',
  //     'lat': 38.438079704940925,
  //     'lng': -122.68715280352382,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '1300 Farmers Lane',
  //       'city': 'Santa Rosa CA 95405',
  //       'storeId': 'PM #3002',
  //       "open": '4:30AM - 11:00PM',
  //       'products': ['alcohol', 'diesel']
  //     }
  //   },

  //   {
  //     'type': 'Feature',
  //     'lat': 38.38699791279503,
  //     'lng': -122.71412270352587,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '3825 Santa Rosa Ave',
  //       'city': 'Santa Rosa CA 95407',
  //       'storeId': 'PM #3001',
  //       "open": '4:30AM - 11:00PM',
  //       'products': ['propane', 'alcohol', 'diesel']
  //     }
  //   },


  //   {
  //     'type': 'Feature',
  //     'lat': 39.043200758540785,
  //     'lng': -122.77576673233318,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '12589 E. Hwy 20',
  //       'city': 'Clearlake Oaks CA 95423',
  //       'storeId': 'PM #3003',
  //       "open": '4:30AM - 11:00PM',
  //       'products': ['propane', 'alcohol', 'diesel', 'e58']
  //     }
  //   },


  //   {
  //     'type': 'Feature',
  //     'lat': 39.08825085842541,
  //     'lng': -122.79372100349515,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '6282 Hwy 20',
  //       'city': 'Lucerne CA 95458',
  //       'storeId': 'PM #3006',
  //       "open": '4:30AM - 11:00PM',
  //       'products': ['propane', 'alcohol', 'diesel']
  //     }
  //   },


  //   {
  //     'type': 'Feature',
  //     'lat': 39.07140730183729,
  //     'lng': -122.91461063233184,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '2935 Lakeshore Blvd',
  //       'city': 'Lakeport CA 95453',
  //       'storeId': 'PM #3005',
  //       "open": '4:30AM - 11:00PM',
  //       'products': ['propane', 'alcohol', 'diesel',]
  //     }
  //   },

  //   {
  //     'type': 'Feature',
  //     'lat': 39.04132656384656,
  //     'lng': -122.9150498476777,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '202 S. Main St.',
  //       'city': 'Lakeport CA 95453',
  //       'storeId': 'PM #3008',
  //       "open": '5:00AM - 10:00PM',
  //       'products': ['propane', 'alcohol']
  //     }
  //   },


  //   {
  //     'type': 'Feature',
  //     'lat': 39.03319635287959,
  //     'lng': -122.92504617466128,
  //     'geometry': {
  //       'type': 'Point'
  //     },
  //     'properties': {
  //       'address': '1088 Lakeport Blvd.',
  //       'city': 'Lakeport CA 95453',
  //       'storeId': 'PM #3007',
  //       "open": '4:30AM - 11:00PM',
  //       'products': ['propane', 'alcohol', 'diesel', 'e58']
  //     }
  //   },









  // ]
}

export default {
  CategoryListData
}
